
	NOLIST
; PicBasic Pro Compiler 2.42, (c) 1998, 2002 microEngineering Labs, Inc. All Rights Reserved. 

LABEL?L macro Label
        RST?RP
    ifdef PM_USED
        LALL
Label
        XALL
    else
Label
    endif
    endm

GOTO?L macro Label
        L?GOTO  Label
    endm

PAUSE?C macro Cin
    if (high (Cin) == 0)
        MOVE?CA Cin
        L?CALL  PAUSE
    else
        MOVE?CB high (Cin), R1 + 1
        MOVE?CA low (Cin)
        L?CALL  PAUSEL
    endif
    endm
PAUSE_USED = 1

PULSOUT?TB macro Regin, Bitin, Bin
        MOVE?BW Bin, R0
        BIT?FW  Regin, Bitin
        L?CALL  PULSOUTT
    endm
PULSOUTT_USED = 1

SERIN?B macro Bout
        L?CALL  SERIN
        MOVE?AB Bout
    endm
SERIN_USED = 1

SERMODE?C macro Cin
        MOVE?CB Cin, GOP
    endm

SERPIN?T macro Regin, Bitin
        BIT?R1  Regin, Bitin
    endm


	LIST
